### ISSUE TITLE
ImportError: No module named _common

### ISSUE THREAD

**Issue by RafalSkolasinski** [conda-forge/fenics-feedstock#15]
I tried to install ``fenics`` into conda env 
```
name: fenics
channels:
  - conda-forge
dependencies:
  - python=2.7
  - anaconda==4.2
  - fenics=2016.1.0
```

and hit following import problem:
```
(fenics) desktop-rskolasinski:~> ipython
Python 2.7.12 | packaged by conda-forge | (default, Sep  8 2016, 14:22:31) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import fenics
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1ecb0c01ef73> in <module>()
----> 1 import fenics

/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/site-packages/fenics/__init__.py in <module>()
      5 """
      6 
----> 7 from dolfin import *

/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/site-packages/dolfin/__init__.pyc in <module>()
     15 
     16 # Import names from the compiled cpp modules
---> 17 from . import cpp
     18 from dolfin.cpp import *
     19 from dolfin.cpp import __version__, __swigversion__, __pythonversion__

/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/site-packages/dolfin/cpp/__init__.py in <module>()
     41 
     42     # Import the module
---> 43     exec("from . import %s" % module_name)
     44     module = globals()[module_name]
     45 

<string> in <module>()

/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/site-packages/dolfin/cpp/common.py in <module>()
     23         except ImportError:
     24             return importlib.import_module('_common')
---> 25     _common = swig_import_helper()
     26     del swig_import_helper
     27 elif _swig_python_version_info >= (2, 6, 0):

/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/site-packages/dolfin/cpp/common.py in swig_import_helper()
     22             return importlib.import_module(mname)
     23         except ImportError:
---> 24             return importlib.import_module('_common')
     25     _common = swig_import_helper()
     26     del swig_import_helper

/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: No module named _common
```

**Comment by garth-wells** [comment]
Hmm, works fine for me on https://notebooks.azure.com.

**Comment by minrk** [comment]
@RafalSkolasinski what's the host OS / version?

**Comment by RafalSkolasinski** [comment]
It's a bit ancient but still supported:
```
desktop-rskolasinski:~> uname -a
Linux desktop-rskolasinski 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mikaem** [comment]
Does it work with python 3? You have a python 3 anaconda version as default, right? 
Could you perhaps go to `/home/rskolasinski/miniconda3/envs/fenics/lib/python2.7/site-packages/dolfin/cpp/`and do `import _common`? could give some more info on what goes wrong.

**Comment by RafalSkolasinski** [comment]
Okay, I tried also on newer os (Mint 18)
```
Linux machine42 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

it doesn't work in both Python 2 and Python 3 env.

When I got to the folder you specified and try to ``import _common`` I got
```
In [1]: import _common
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-24a33b047181> in <module>()
----> 1 import _common

ImportError: libboost_filesystem.so.1.61.0: cannot open shared object file: No such file or directory
```

**Comment by mikaem** [comment]
Weird, boost=1.61.* is a listed runtime dependency for fenics. You should have it under `/home/rskolasinski/miniconda3/envs/fenics/lib/`. Could you check? Perhaps show us the entire log from the installation of the environment?

**Comment by mikaem** [comment]
I can reproduce this on a continuumio/miniconda3 docker (https://hub.docker.com/r/continuumio/). The boost installed is for some reason from the defaults channel and it's version 1.60. With an additional `conda install -c conda-forge boost=1.61` everything works just fine.

**Comment by RafalSkolasinski** [comment]
Yes, installing ``boost=1.6.1`` from ``conda-forge`` solves the issue. However it must be ``1.6.1``. I only did first
```
conda install -c conda-forge boost
```
which installed ``1.6.2`` and had same import problem as in the beginning.

**Comment by minrk** [comment]
#21 pins boost to 1.62, which should fix this. I'm not sure why conda allowed 1.62 to be installed with the previous version, since that violates the dependencies of the package. Seems like it would have to be a bug in conda to allow that to happen.

**Comment by trbedwards** [comment]
I'm having problems getting fenics installed, due to the ModuleNotFoundError. I tried installing boost 1.61, but then I got Unsatisfiable errors because of a conflict between boost 1.61 and ciaro. Then I tried downgrading fenics to 2016.2 and got the same error. Again I tried installing boost 1.61, and now it conflicts with matplotlib. I'm hesitant to uninstall matplotlib, as I'm worried that when I reinstall it then it will need to update boost to a version that conflicts with fenics. 

Please help!

For more information, I am using Anaconda Python 3.6 on Ubuntu 17.10, 64 bit. I tried installing the ubuntu apt package for fenics, but I was unable to import dolfin from python (probably it's installed on the default system python rather than anaconda's?). After that, I installed the conda-forge distribution, but this led me to the _common import error.

**Comment by minrk** [comment]
@trbedwards can you install 2017.2.0? Can you include your `conda list`? For older versions of fenics, this has been the result of insufficient pinning, so some packages (e.g. boost) needed to be pinned-down more strictly. I *believe* the pinning in the latest build of the package is sufficiently strict to avoid these problems, but the same may not be true of 2016.x

**Comment by trbedwards** [comment]
I believe it was the latest version, 2017.2.0, installed by using the command:
`conda install -c conda-forge fenics`. 
I'll double check tonight when I have a stable wifi and include the result of `conda list`.

**Comment by trbedwards** [comment]
I can confirm that I installed fenics 2017.2.0, and I still get this error when import dolfin:
`ModuleNotFoundError: No module named '_common'`

The output from `conda list` is:
```
# packages in environment at /home/tedwards/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0  
alabaster                 0.7.10           py36h306e16b_0  
alembic                   0.9.6                     <pip>
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.5            py36h19c0dcd_0  
anaconda-navigator        1.6.9            py36h11ddaaa_0  
anaconda-project          0.8.0            py36h29abdf5_0  
asn1crypto                0.22.0           py36h265ca7c_1  
astroid                   1.5.3            py36hbdb9df2_0  
astropy                   2.0.2            py36ha51211e_4  
babel                     2.5.0            py36h7d14adf_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bitarray                  0.8.1            py36h5834eb8_0  
bkcharts                  0.2              py36h735825a_0  
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.0.0            py36h688b259_0  
bokeh                     0.12.10          py36hbb0e44a_0  
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
boto                      2.48.0           py36h6e4cd66_1  
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h0376d23_1  
ca-certificates           2018.1.18                     0    conda-forge
cairo                     1.14.10              haa5651f_5  
certifi                   2018.1.18                py36_0    conda-forge
cffi                      1.10.0           py36had8d393_1  
chardet                   3.0.4            py36h0f667ec_1  
ciso8601                  1.0.5                     <pip>
click                     6.7              py36h5253387_0  
cloog                     0.18.0                        0  
cloudpickle               0.4.0            py36h30f8c20_0  
clyent                    1.2.2            py36h7e57e65_1  
cmake                     3.9.4                h142f0e9_0  
colorama                  0.3.9            py36h489cec4_0  
conda                     4.4.6                    py36_0  
conda-build               3.0.27           py36h940a66d_0  
conda-env                 2.6.0                h36134e3_1  
conda-verify              2.0.0            py36h98955d8_0  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.0.3            py36ha225213_1  
curl                      7.55.1               hcb0b314_2  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.26.1           py36h21c49d0_0  
cytoolz                   0.8.2            py36h708bfd4_0  
dask                      0.15.3           py36hdc2c8aa_0  
dask-core                 0.15.3           py36h10e6167_0  
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.10.22              h3b5a359_0  
decorator                 4.1.2            py36hd076ac8_0  
distributed               1.19.1           py36h25f3894_0  
docutils                  0.14             py36hb0f60f5_0  
dominate                  2.3.1                     <pip>
eigen                     3.3.3                         0    conda-forge
entrypoints               0.2.3            py36h1aec115_2  
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.4                hc00ebd1_1  
fastcache                 1.0.2            py36h5b0c431_0  
fenics                    2017.2.0            np113py36_3    conda-forge
filelock                  2.0.12           py36hacfa1f5_0  
flask                     0.12.2           py36hb24657c_0  
Flask-Bootstrap           3.3.7.1                   <pip>
Flask-Caching             1.3.3                     <pip>
flask-cors                3.0.3            py36h2d857d3_0  
Flask-HTTPAuth            3.2.3                     <pip>
Flask-Login               0.4.0                     <pip>
Flask-Migrate             2.1.1                     <pip>
flask-nav                 0.6                       <pip>
Flask-Script              2.0.6                     <pip>
Flask-SQLAlchemy          2.3.2                     <pip>
Flask-WTF                 0.14.2                    <pip>
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8                  h52ed37b_0  
gcc                       4.8.5                         7  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.2.2            py36h2fe25dc_0  
glib                      2.53.6               hc861d11_1  
glob2                     0.5              py36h2c1b292_1  
gmp                       6.1.2                hb3b607b_0  
gmpy2                     2.0.8            py36h55090d7_1  
graphite2                 1.3.10               hc526e54_0  
greenlet                  0.4.12           py36h2d503a6_0  
gst-plugins-base          1.12.2               he3457e5_0  
gstreamer                 1.12.2               h4f93127_0  
h5py                      2.7.0            py36he81ebca_1  
harfbuzz                  1.5.0                h2545bd6_0  
hdf5                      1.10.1               hb0523eb_0  
heapdict                  1.0.0            py36h79797d7_0  
html5lib                  0.999999999      py36h2cfc398_0  
hypre                     2.11.2                        1    conda-forge
icu                       58.2                 h211956c_0  
idna                      2.6              py36h82fb2a8_1  
imageio                   2.2.0            py36he555465_0  
imagesize                 0.7.1            py36h52d8127_0  
intel-openmp              2018.0.0             h15fc484_7  
ipykernel                 4.6.1            py36hbf841aa_0  
ipython                   6.1.0            py36hc72a948_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.0.0            py36h7b55c3a_0  
isl                       0.12.2                        0  
isort                     4.2.15           py36had401c0_0  
itsdangerous              0.24             py36h93cc618_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.3              py36h4c697fb_0  
jedi                      0.10.2           py36h552def0_0  
jinja2                    2.9.6            py36h489bce4_1  
jpeg                      9b                   habf39ab_1  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.1.0            py36h614e9ea_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.3.0            py36h357a921_0  
jupyterlab                0.27.0           py36h86377d0_2  
jupyterlab_launcher       0.4.0            py36h4d8058d_0  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                h4deb6c0_3  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h9f7466a_2  
libpng                    1.6.32               hda9c8bc_2  
libsodium                 1.0.13               h31c71d8_2  
libssh2                   1.8.0                h8c220ad_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.8                h90200ff_9  
libtool                   2.4.6                hd50d1a6_0  
libuv                     1.19.2                        0    conda-forge
libxcb                    1.12                 h84ff03f_3  
libxml2                   2.9.4                h6b072ca_5  
libxslt                   1.1.29               hcf9102b_5  
llvmlite                  0.20.0                   py36_0  
locket                    0.2.0            py36h787c0ad_1  
lxml                      4.1.0            py36h5b66e50_0  
lzo                       2.10                 h1bfc0ba_1  
Mako                      1.0.7                     <pip>
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.1.0            py36hba5de38_0  
mccabe                    0.6.1            py36h5ad9710_1  
metis                     5.1.0                         3    conda-forge
mistune                   0.7.4            py36hbab8784_0  
mkl                       2018.0.0             hb491cac_4  
mkl-service               1.1.2            py36h17a0993_4  
mock                      2.0.0            py36h3c5bf6c_0  
mpc                       1.0.3                hf803216_4  
mpfr                      3.1.5                h12ff648_1  
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                         0    conda-forge
mpmath                    0.19             py36h8cc018b_2  
msgpack-python            0.4.8            py36hec4c5d1_0  
multipledispatch          0.4.9            py36h41da3fb_0  
mumps-mpi                 5.0.2           blas_openblas_0  [blas_openblas]  conda-forge
navigator-updater         0.1.0            py36h14770f7_0  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.0                  h06874d7_1  
networkx                  2.0              py36h7e96fb8_0  
nltk                      3.2.4            py36h1a0979f_0  
nose                      1.3.7            py36hcdf7029_2  
notebook                  5.0.0            py36h0b20546_2  
numba                     0.35.0             np113py36_10  
numexpr                   2.6.2            py36hdd3393f_1  
numpy                     1.13.3          py36_blas_openblas_201  [blas_openblas]  conda-forge
numpydoc                  0.7.0            py36h18f165f_0  
odo                       0.5.1            py36h90ed295_0  
olefile                   0.44             py36h79f9f78_0  
openblas                  0.2.20                        7    conda-forge
openpyxl                  2.4.8            py36h41dd2a8_1  
openssl                   1.0.2n                        0    conda-forge
packaging                 16.8             py36ha668100_1  
pandas                    0.20.3           py36h842e28d_2  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
pango                     1.40.11              h8191d47_0  
parmetis                  4.0.3                         0    conda-forge
partd                     0.3.8            py36h36fd896_0  
patchelf                  0.9                  hf79760b_2  
path.py                   10.3.1           py36he0c6f6d_0  
pathlib2                  2.3.0            py36h49efa8e_0  
patsy                     0.4.1            py36ha3be15e_0  
pbr                       3.1.1            py36hb5f6b33_0  
pcre                      8.41                 hc71a17e_0  
pep8                      1.7.0            py36h26ade29_0  
petsc                     3.8.3           blas_openblas_1  [blas_openblas]  conda-forge
petsc4py                  3.8.1                    py36_1    conda-forge
pexpect                   4.2.1            py36h3b9d41b_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    4.2.1            py36h9119f52_0  
pip                       9.0.1            py36h8ec8b28_3  
pixman                    0.34.0               h83dc358_2  
pkg-config                0.29.2                        1    conda-forge
pkginfo                   1.4.1            py36h215d178_1  
ply                       3.10             py36hed35086_0  
profilehooks              1.9.0                     <pip>
prompt_toolkit            1.0.15           py36h17d85b1_0  
psutil                    5.4.0            py36h84c53db_0  
ptscotch                  6.0.4                         6    conda-forge
ptyprocess                0.5.2            py36h69acd42_0  
py                        1.4.34           py36h0712aa3_1  
pycodestyle               2.3.1            py36hf609f19_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h6998063_1  
pycurl                    7.43.0           py36h5e72054_3  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygments                  2.2.0            py36h0d3125c_0  
pylint                    1.7.4            py36hb9d4533_0  
pyodbc                    4.0.17           py36h999153c_0  
pyopenssl                 17.2.0           py36h5cc804b_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5  
pysocks                   1.6.7            py36hd97a5b1_1  
pytables                  3.4.2            py36h3b5282a_2  
pytest                    3.2.1            py36h11ad3bb_1  
python                    3.6.3                hc9025b9_1  
python-dateutil           2.6.1            py36h88d3b88_1  
python-editor             1.0.3                     <pip>
pytz                      2017.2           py36hc2ccc2a_1  
pywavelets                0.5.2            py36he602eb0_0  
pyyaml                    3.12             py36hafb9ca4_1  
pyzmq                     16.0.2           py36h3b0cf96_2  
qt                        5.6.2               h974d657_12  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.3.1            py36h3691cc8_0  
readline                  7.0                  hac23ff0_3  
recordclass               0.4.3                     <pip>
requests                  2.18.4           py36he2e5f8d_1  
rhash                     1.3.4                         0    conda-forge
rope                      0.10.5           py36h1f8c17e_0  
ruamel_yaml               0.11.14          py36ha2fb22d_2  
scalapack                 2.0.2                         1    conda-forge
scikit-image              0.13.0           py36had3c07a_1  
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
scotch                    6.0.4                         4    conda-forge
seaborn                   0.8.0            py36h197244f_0  
setuptools                36.5.0           py36he42e2e1_0  
simplegeneric             0.8.1            py36h2cb9092_0  
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.18.1           py36h51ed4ed_2  
six                       1.11.0           py36h372c433_1  
slepc                     3.8.2           blas_openblas_0  [blas_openblas]  conda-forge
slepc4py                  3.8.0                    py36_0    conda-forge
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.5.3            py36h3c761f9_0  
sortedcontainers          1.5.7            py36hdf89491_0  
sphinx                    1.6.3            py36he5f0bdb_0  
sphinx-rtd-theme          0.2.4                     <pip>
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.4            py36hbe6152b_0  
sqlalchemy                1.1.13           py36hfb5efd7_0  
sqlite                    3.20.1               h6d8b0f3_1  
statsmodels               0.8.0            py36h8533d0b_0  
suitesparse               4.5.4           blas_openblas_201  [blas_openblas]  conda-forge
swig                      3.0.12                        2    conda-forge
sympy                     1.1.1            py36hc6d1c1c_0  
tbb                       2018_20171205                 0    conda-forge
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.6              py36ha25a19f_0  
testpath                  0.3.1            py36h8cadb63_0  
tinynumpy                 1.2.1                     <pip>
tk                        8.6.7                h5979e9b_1  
toolz                     0.8.2            py36h81f2dff_0  
tornado                   4.5.2            py36h1283b2a_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.2            py36h7da032a_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.4                hc36303a_1  
urllib3                   1.22             py36hbe7ace6_0  
visitor                   0.1.3                     <pip>
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
werkzeug                  0.12.2           py36hc703753_0  
wheel                     0.29.0           py36he7f4e38_1  
widgetsnbextension        3.0.2            py36hd01bb71_1  
wrapt                     1.10.11          py36h28b7045_0  
WTForms                   2.1                       <pip>
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.2            py36h3de1aca_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.3                h2bcbf08_1  
yaml                      0.1.7                h96e3832_1  
zeromq                    4.2.2                hb0b69da_1  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               hfbfcf68_1 
```

**Comment by waynezw0618** [comment]
anyone fix that ?
I am using conda to install Fenics with python2.7 
here is the my conda list
`# All requested packages already installed.

(fenicsproject) weis-mbp:baseline_flow weizhang$ conda list
# packages in environment at /anaconda2/envs/fenicsproject:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    py27_0  
astor                     0.7.1                    py27_0  
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   pypi_0    pypi
backports                 1.0                        py_2  
backports.weakref         1.0.post1                  py_1  
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py27_0    conda-forge
boost                     1.61.0                   py27_2    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
c-ares                    1.15.0               h1de35cc_1  
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_0    conda-forge
cmake                     3.14.5               hdd2e4aa_0    conda-forge
configparser              3.7.4                    pypi_0    pypi
contextlib2               0.5.5                    pypi_0    pypi
curl                      7.64.1               h22ea746_0    conda-forge
dijitso                   2016.1.0                 pypi_0    pypi
eigen                     3.3.7             h04f5b5a_1000    conda-forge
enum34                    1.1.6                    py27_1  
expat                     2.2.5             h6de7cb9_1003    conda-forge
fastcache                 1.1.0            py27h01d97ff_0    conda-forge
fenics                    2016.1.0                 py27_5    conda-forge
fiat                      2016.1.0                 pypi_0    pypi
funcsigs                  1.0.2            py27hb9f6266_0  
futures                   3.2.0                    py27_0  
gast                      0.2.2                    py27_0  
gmp                       6.1.2             h0a44026_1000    conda-forge
gmpy2                     2.1.0b1          py27h1744cca_0    conda-forge
grpcio                    1.16.1           py27h044775b_1  
hdf5                      1.10.4               hfa1e0ec_0  
html5lib                  0.9999999                py27_0    conda-forge
icu                       56.1                          4    conda-forge
importlib-metadata        0.18                     pypi_0    pypi
instant                   2016.1.0                 pypi_0    pypi
krb5                      1.16.3            hcfa6398_1001    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15              h01d97ff_1005    conda-forge
libopenblas               0.2.20               hdc02c5d_7  
libprotobuf               3.8.0                hd9629dc_0  
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libuv                     1.30.0               h01d97ff_0    conda-forge
markdown                  3.1.1                    py27_0  
metis                     5.1.0             h0a44026_1003    conda-forge
mock                      3.0.5                    py27_0  
more-itertools            5.0.0                    pypi_0    pypi
mpc                       1.1.0             h3aece09_1006    conda-forge
mpfr                      4.0.2                h0a95893_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             ha90c164_1012    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
ncurses                   6.1                  h0a44026_1  
numpy                     1.15.0          py27_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        4  
openblas-devel            0.2.20                        7  
openssl                   1.1.1b               h01d97ff_2    conda-forge
packaging                 19.0                     pypi_0    pypi
pathlib2                  2.3.4                    pypi_0    pypi
pcre                      8.41              h0a44026_1003    conda-forge
petsc                     3.7.4           blas_openblas_1  [blas_openblas]  conda-forge
petsc4py                  3.7.0                    py27_1    conda-forge
pillow                    6.0.0                    pypi_0    pypi
pip                       19.1.1                   py27_0  
pkg-config                0.29.2            h112b980_1005    conda-forge
pluggy                    0.12.0                   pypi_0    pypi
ply                       3.11                       py_1    conda-forge
printind                  4.0                      pypi_0    pypi
protobuf                  3.8.0            py27h0a44026_0  
ptscotch                  6.0.6             ha54644a_1002    conda-forge
py                        1.8.0                    pypi_0    pypi
pyparsing                 2.4.0                    pypi_0    pypi
pytest                    4.6.3                    pypi_0    pypi
python                    2.7.15            h932b40d_1008    conda-forge
readline                  7.0                  h1de35cc_5  
rhash                     1.3.6             h1de35cc_1001    conda-forge
scandir                   1.10.0                   pypi_0    pypi
scipy                     1.2.2                    pypi_0    pypi
scotch                    6.0.6             hde27766_1002    conda-forge
setuptools                41.0.1                   py27_0  
six                       1.12.0                   py27_0  
slepc                     3.7.4                         0    conda-forge
slepc4py                  3.7.0                    py27_0    conda-forge
sqlite                    3.28.0               ha441bb4_0  
suitesparse               4.5.6           blas_openblash55dcaef_201  [blas_openblas]  conda-forge
swig                      4.0.0                h6de7cb9_0    conda-forge
sympy                     1.4                      py27_0    conda-forge
tbb                       2019.7               h770b8ee_0    conda-forge
tensorboard               1.8.0                    py27_1    conda-forge
tensorflow                1.8.0                    py27_1    conda-forge
tensorforce               0.4.2                    pypi_0    pypi
termcolor                 1.1.0                    py27_1  
tk                        8.6.9             h2573ce8_1002    conda-forge
ufl                       2016.1.0                 pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    py27_1  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py27_0  
xz                        5.2.4             h1de35cc_1001    conda-forge
zipp                      0.5.1                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3  
(fenicsproject) weis-mbp:baseline_flow weizhang$ 
`
